Polymer 2
MergeMyPullRequest/order-splitter pull request #6
Opened 2017-05-23 01:42 UTC by billy-hardy

relates to #3

2017-05-23 17:13 UTC, jonsmithers requested changes

2017-05-23 17:13 UTC, jonsmithers commented on common/orderData.js
> +window.OrderData = OrderData;
Is OrderData not already in the global scope?

2017-05-23 17:13 UTC, jonsmithers commented on elements/example-order.html
> +
Instead of adding to the class to the global scope and then never using it again, you can just pass it directly by declaring it here instead of above.

2017-05-23 17:13 UTC, jonsmithers commented on .gitignore
> +bower_components
does this folder exist? I thought bower_components were in `common/`.

2017-05-23 17:13 UTC, jonsmithers commented on elements/example-order.html
> +
Eh, I suppose this is reasonable.

2017-05-23 17:15 UTC, jonsmithers commented on common/orderData.js
> +window.OrderData = OrderData;
Could this just be consolidated into ExampleOrder?

2017-05-23 17:17 UTC, jonsmithers requested changes

2017-05-23 17:17 UTC, jonsmithers commented on common/data/orderUp.json
> +]
Can this just be plaintext? You can make requests that use text instead of JSON.

2017-05-23 19:23 UTC, jonsmithers commented on webclient/elements
> +../elements
`webclient/elements` symlinks to the root directory, but `webclient/data` symlinks to the common directory. Why the inconsistency?

2017-05-23 19:37 UTC, billy-hardy commented on .gitignore
> +bower_components
if you don't prepend it with a /, then it recursively ignores the file names. So it'll catch common/bower_components

2017-05-23 19:50 UTC, billy-hardy commented on common/orderData.js
> +window.OrderData = OrderData;
the getData can definitely go into ExampleOrder, but what about making the parse function into a Stream Transformer?

2017-05-29 22:47 UTC, billy-hardy commented on webclient/elements
> +../elements
all symlinks have been removed. We now always have to build to run the app

2017-05-29 22:49 UTC, billy-hardy commented on common/data/orderUp.json
> +]
This has been changed to allow all example orders to be defined in the file, and json would help manipulating that data greatly. We could have the actual order not defined as an array (instead as just a string), but I think it is hard to deal with as is (in terms of developer reading it), and a single string would just exacerbate that. Thoughts?

2017-05-29 22:50 UTC, billy-hardy commented on common/orderData.js
> +window.OrderData = OrderData;
Consolidated them. Perhaps a Stream Transformer can be a future optimization

2017-06-07 16:23 UTC, jonsmithers approved these changes

2017-06-07 16:25 UTC, merged